"""`taskdistill demo`: the whole pipeline on a bundled task, composed from the public commands.

There is no demo-only code path: the demo imports data with the importer `capture --import` uses,
sends the training inputs through the real capture proxy, then calls the same functions as `curate`,
`train`, `eval --select`, `serve` and `report`. The only demo-specific parts are the datasets, the
split assignment (in code, as ``meta.split``) and the fixed smoke-test queries.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import socket
import threading
import time
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import httpx

from taskdistill import paths
from taskdistill.config import TaskSpec, load_task
from taskdistill.teacher.request_key import canonical_json, request_key
from taskdistill.teacher.requests import build_teacher_request

DEMOS = ("banking77", "invoices")
STAGES = ("data", "capture", "curate", "train", "eval", "serve", "report")
PROFILES = ("quick", "full")
SMOKE_QUERIES = 20
CAPTURE_PORT = 8787
SERVE_PORT = 8000
CAPTURE_CONCURRENCY = 8


class DemoError(RuntimeError):
    pass


@dataclass
class DemoData:
    """Rows per split as import records ({"input", "gold", "meta"}), plus the dataset card facts."""

    records: dict[str, list[dict[str, Any]]]
    card_info: dict[str, Any]
    smoke: list[str] = field(default_factory=list)


# ------------------------------------------------------------------------------------------ datasets
def load_demo_data(name: str, profile: str) -> DemoData:
    """The demo dataset for a profile; the quick profile is a fixed subset of the full splits."""
    if name == "banking77":
        from taskdistill.demos import banking77 as b77

        data = b77.fetch_banking77()
        splits = b77.profile_splits(b77.demo_splits(data), profile)  # type: ignore[arg-type]
        records: dict[str, list[dict[str, Any]]] = {str(split): b77.to_records(rows) for split, rows in splits.items()}
        quick_test = b77.profile_splits(b77.demo_splits(data), "quick")["test"]
        card = {
            "name": "Banking77 (demo)",
            "source": b77.SOURCE_URL if data.source == "github" else b77.HUB_URL,
            "licence": b77.LICENCE,
            "attribution": b77.ATTRIBUTION,
            "citation": b77.CITATION,
            "split_rule": "official test set -> test; official train set -> 90/10 train/valid, stratified by gold "
            "label with seed 13",
        }
        smoke_pool = [row.text for row in quick_test]
    elif name == "invoices":
        from taskdistill.demos import invoices as inv

        docs = inv.generate()
        by_split: dict[str, list[Any]] = {"train": [], "valid": [], "test": []}
        for doc in docs:
            by_split[doc.split].append(doc)
        if profile == "quick":
            by_split = {str(split): list(inv.quick_subset(rows, split)) for split, rows in by_split.items()}
        records = {str(split): [inv.doc_to_record(doc) for doc in rows] for split, rows in by_split.items()}
        card = {
            "name": "Synthetic invoices (demo)",
            "source": "generated by taskdistill.demos.invoices (seed 7, standard library only)",
            "licence": "Apache-2.0 (part of the taskdistill repository)",
            "attribution": "Synthetic documents: fictional companies, reserved contact data (RFC 2606/5737, 555-01xx).",
            "split_rule": "by template: train 10 email + 10 layout templates, valid 2 + 2, test 3 + 3",
        }
        smoke_pool = [doc.text for doc in inv.quick_subset([d for d in docs if d.split == "test"], "test")]
    else:
        raise DemoError(f"unknown demo {name!r}; choose one of {', '.join(DEMOS)}")
    return DemoData(records=records, card_info=card, smoke=smoke_queries(smoke_pool))


def smoke_queries(pool: list[str], n: int = SMOKE_QUERIES) -> list[str]:
    """A fixed spread of test inputs (from the quick test subset, so both profiles have them)."""
    if not pool:
        return []
    step = max(1, len(pool) // n)
    return pool[::step][:n]


def demo_requests(name: str, spec: TaskSpec) -> list[dict[str, Any]]:
    """Every teacher request the demo can send, in both profiles (the full splits contain the quick ones)."""
    data = load_demo_data(name, "full")
    texts = [record["input"] for rows in data.records.values() for record in rows]
    return [build_teacher_request(spec, text) for text in texts]


# ------------------------------------------------------------------------------------------ servers
def free_port(preferred: int) -> int:
    """``preferred`` when it is free on 127.0.0.1, else an ephemeral free port."""
    for port in (preferred, 0):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            try:
                sock.bind(("127.0.0.1", port))
            except OSError:
                continue
            return int(sock.getsockname()[1])
    raise DemoError("no free local port")


@contextlib.contextmanager
def background_server(app: Any, port: int) -> Iterator[str]:
    """Run an ASGI app with uvicorn in a thread; yields its base URL."""
    import uvicorn

    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="error", lifespan="on")
    server = uvicorn.Server(config)
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()
    deadline = time.monotonic() + 60
    while not server.started:
        if not thread.is_alive():
            raise DemoError(f"server on port {port} failed to start")
        if time.monotonic() > deadline:
            raise DemoError(f"server on port {port} did not start within 60 s")
        time.sleep(0.05)
    try:
        yield f"http://127.0.0.1:{port}"
    finally:
        server.should_exit = True
        thread.join(timeout=30)


# ------------------------------------------------------------------------------------------ stages
@dataclass
class DemoContext:
    name: str
    profile: str
    spec: TaskSpec
    mode: str
    yes: bool
    max_usd: float | None
    backend: str
    base: str | None
    seed: int | None
    log: Callable[[str], Any]
    data: DemoData | None = None
    timings: dict[str, float] = field(default_factory=dict)
    run_id: str | None = None

    @property
    def marker(self) -> Path:
        return paths.task_home(self.spec.task) / "demo_state.json"


def _data_digest(data: DemoData) -> str:
    return hashlib.sha256(canonical_json(data.records)).hexdigest()


def _read_state(ctx: DemoContext) -> dict[str, Any]:
    try:
        return dict(json.loads(ctx.marker.read_text(encoding="utf-8")))
    except (OSError, ValueError):
        return {}


def _write_state(ctx: DemoContext, **update: Any) -> None:
    state = _read_state(ctx)
    state.update(update)
    ctx.marker.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def stage_data(ctx: DemoContext) -> None:
    """Load the dataset and import every split's inputs with gold labels and meta.split (`capture --import`)."""
    from taskdistill.capture.importer import import_file
    from taskdistill.store import Store

    ctx.data = load_demo_data(ctx.name, ctx.profile)
    state = _read_state(ctx)
    other = state.get("profile")
    if other and other != ctx.profile:
        raise DemoError(
            f"this workspace already holds the {other} profile of the {ctx.name} demo; run each profile in its own "
            f"workspace, e.g. TASKDISTILL_HOME=./.taskdistill-{ctx.profile}"
        )
    digest = _data_digest(ctx.data)
    counts = {split: len(rows) for split, rows in ctx.data.records.items()}
    if state.get("imported") == digest:
        ctx.log(f"      already imported: {counts}")
        return
    import_dir = paths.task_home(ctx.spec.task) / "demo_import"
    import_dir.mkdir(parents=True, exist_ok=True)
    store = Store()
    for split, rows in ctx.data.records.items():
        path = import_dir / f"{split}.inputs.jsonl"
        with path.open("w", encoding="utf-8") as fh:
            for row in rows:
                fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        result = import_file(store, ctx.spec.task, path, "inputs")
        ctx.log(f"      imported {result['imported']} {split} inputs with gold labels (--format inputs)")
    _write_state(ctx, profile=ctx.profile, imported=digest, counts=counts)


def _teacher(ctx: DemoContext, phase: str) -> Any:
    from taskdistill.teacher.factory import make_teacher, new_run_id

    return make_teacher(ctx.spec, mode=ctx.mode, phase=phase, run_id=new_run_id(f"demo-{phase}"), run_cap=ctx.max_usd)


def stage_capture(ctx: DemoContext) -> None:
    """Send the training inputs through the real capture proxy, as the application would."""
    from taskdistill.capture.proxy import create_proxy_app
    from taskdistill.store import Store
    from taskdistill.teacher.upstream import create_upstream_app

    assert ctx.data is not None
    store = Store()
    seen = {row.request_key for row in store.iter_captures(ctx.spec.task) if row.captured}
    bodies = [build_teacher_request(ctx.spec, r["input"]) for r in ctx.data.records["train"]]
    todo = [b for b in bodies if request_key(b) not in seen]
    if not todo:
        ctx.log(f"      all {len(bodies)} training requests already captured")
        return
    if ctx.mode == "live":
        _confirm_live_capture(ctx, todo)
    teacher = _teacher(ctx, "demo-capture")
    proxy_port = free_port(CAPTURE_PORT)
    upstream_port = free_port(0)
    while upstream_port == proxy_port:  # both probes closed their sockets; never hand out one port twice
        upstream_port = free_port(0)
    if proxy_port != CAPTURE_PORT:
        ctx.log(f"      port {CAPTURE_PORT} is taken; the capture proxy uses {proxy_port}")
    api_key = ctx.spec.teacher.api_key() if ctx.mode == "live" else "replay"
    try:
        with background_server(create_upstream_app(teacher, models=[ctx.spec.teacher.model]), upstream_port) as up:
            proxy = create_proxy_app(store, f"{up}/v1", default_task=ctx.spec.task)
            with background_server(proxy, proxy_port) as proxy_url:
                ctx.log(f"      application -> capture proxy {proxy_url}/t/{ctx.spec.task}/v1 -> teacher ({ctx.mode})")
                failures = asyncio.run(_send_all(f"{proxy_url}/t/{ctx.spec.task}/v1", todo, api_key))
    finally:
        asyncio.run(teacher.aclose())
    if failures:
        raise DemoError(f"{len(failures)} captured requests failed; first: {failures[0]}")
    counts = store.count_captures(ctx.spec.task)
    ctx.log(f"      captured {len(todo)} requests through the proxy ({counts['captured']} in the store)")


def _confirm_live_capture(ctx: DemoContext, todo: list[dict[str, Any]]) -> None:
    from taskdistill.ledger import worst_case_cost
    from taskdistill.teacher.cache import ResponseCache
    from taskdistill.teacher.client import confirm_spend
    from taskdistill.teacher.factory import load_pricing

    cache = ResponseCache()
    uncached = [b for b in todo if cache.get(request_key(b)) is None]
    if not uncached:
        return
    price = load_pricing().price_for(ctx.spec.teacher.model, ctx.spec.teacher.provider)
    projected = sum(worst_case_cost(b, price) for b in uncached)
    ctx.log(f"      {len(uncached)} uncached live requests, worst-case projection ${projected:.2f}")
    confirm_spend(projected, ctx.yes)


async def _send_all(base_url: str, bodies: list[dict[str, Any]], api_key: str | None) -> list[str]:
    failures: list[str] = []
    semaphore = asyncio.Semaphore(CAPTURE_CONCURRENCY)
    headers = {"Authorization": f"Bearer {api_key or 'none'}"}
    async with httpx.AsyncClient(timeout=httpx.Timeout(300.0, connect=10.0)) as client:

        async def send(body: dict[str, Any]) -> None:
            async with semaphore:
                try:
                    response = await client.post(f"{base_url}/chat/completions", json=body, headers=headers)
                except httpx.HTTPError as exc:
                    failures.append(repr(exc))
                    return
                if response.status_code != 200:
                    failures.append(f"HTTP {response.status_code}: {response.text[:200]}")

        await asyncio.gather(*(send(body) for body in bodies))
    return failures


def stage_curate(ctx: DemoContext) -> None:
    from taskdistill.curate.pipeline import run_curate
    from taskdistill.store import Store

    assert ctx.data is not None
    teacher = _teacher(ctx, "curate-label")
    try:
        result = run_curate(
            ctx.spec,
            store=Store(),
            teacher=teacher,
            yes=ctx.yes,
            max_usd=ctx.max_usd,
            card_info=ctx.data.card_info,
            log=lambda line: ctx.log(f"      {line}"),
        )
    finally:
        asyncio.run(teacher.aclose())
    splits = result.stats.get("splits", {})
    ctx.log("      curated " + ", ".join(f"{k} {v}" for k, v in splits.items()))


def stage_train(ctx: DemoContext) -> None:
    from taskdistill.train.runner import run_training

    result = run_training(
        ctx.spec,
        backend=ctx.backend,
        base=ctx.base,
        profile=ctx.profile,
        seed=ctx.seed,
        labels="teacher",
        log=lambda line: ctx.log(f"      {line}"),
    )
    ctx.run_id = result.run_id
    log = result.log
    ctx.log(
        f"      run {result.run_id}: {log.get('iterations')} iterations in {log.get('wall_seconds', 0):.0f} s, "
        f"best val loss {log.get('best_val_loss')}"
    )


def stage_eval(ctx: DemoContext) -> None:
    from taskdistill.evaluate.runner import run_eval

    result = run_eval(
        ctx.spec,
        split="test",
        backend=ctx.backend,
        select=True,
        fast=ctx.profile == "quick",
        log=lambda line: ctx.log(f"      {line}"),
        command=f"taskdistill demo {ctx.name} --profile {ctx.profile} (eval --select)",
    )
    ctx.run_id = result.get("run_id", ctx.run_id)
    systems = result.get("systems", {})
    metric = "accuracy" if ctx.spec.type == "classification" else "field_micro_f1"
    parts = []
    for system in ("teacher", "student", "cascade", "tfidf"):
        value = (systems.get(system) or {}).get("metrics", {}).get(metric)
        if isinstance(value, float):
            parts.append(f"{system} {value:.3f}")
    ctx.log(f"      test {metric} (gold): " + ", ".join(parts))
    op = (result.get("operating_point") or {}).get("test") or {}
    threshold = (result.get("threshold") or {}).get("threshold")
    ctx.log(
        f"      threshold {threshold} chosen on validation; test escalation {op.get('escalation_rate', 0):.1%}, "
        f"target held: {op.get('met')}"
    )


def stage_serve(ctx: DemoContext) -> None:
    """Start the cascade server, send the fixed smoke queries, print routes and confidences."""
    from taskdistill.serve.runner import build_server

    assert ctx.data is not None
    port = free_port(SERVE_PORT)
    if port != SERVE_PORT:
        ctx.log(f"      port {SERVE_PORT} is taken; the cascade server uses {port}")
    app, banner = build_server(
        ctx.spec,
        threshold="auto",
        backend=ctx.backend,
        replay=ctx.mode == "replay",
        port=port,
        max_usd=ctx.max_usd,
    )
    for line in banner:
        ctx.log(f"      {line}")
    request_path = Path.cwd() / "request.json"
    readme_body = build_teacher_request(ctx.spec, ctx.data.smoke[0])
    request_path.write_text(json.dumps(readme_body, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    with background_server(app, port) as url, httpx.Client(timeout=120.0) as client:
        routes: dict[str, int] = {}
        for i, text in enumerate(ctx.data.smoke, 1):
            body = build_teacher_request(ctx.spec, text)
            response = client.post(f"{url}/v1/chat/completions", json=body)
            route = response.headers.get("x-taskdistill-route", f"HTTP {response.status_code}")
            confidence = response.headers.get("x-taskdistill-confidence", "-")
            routes[route] = routes.get(route, 0) + 1
            content = ""
            if response.status_code == 200:
                content = response.json()["choices"][0]["message"]["content"]
            preview = " ".join(text.split())[:48]
            answer = " ".join(content.split())[:40]
            ctx.log(f"      {i:>2}. {route:<16} conf {confidence:<9} {preview!r} -> {answer}")
    ctx.log("      routes: " + ", ".join(f"{k} {v}" for k, v in sorted(routes.items())))
    ctx.log(
        f"      wrote {request_path.name}: try `curl -s -D - {url.rsplit(':', 1)[0]}:{SERVE_PORT}/v1/chat/completions "
        f"-H 'Content-Type: application/json' -d @request.json` against `taskdistill serve --task {ctx.spec.task}`"
    )


def stage_report(ctx: DemoContext) -> None:
    from taskdistill.report.builder import build_report

    result = build_report(ctx.spec, command=f"taskdistill demo {ctx.name} --profile {ctx.profile}")
    out = Path("reports") / ctx.spec.task
    ctx.log(f"      wrote {out / 'report.md'} and {out / 'report.json'}")
    be = (result.get("break_even") or {}).get("volume")
    if be is not None:
        ctx.log(f"      break-even volume: {be:,.0f} requests")


STAGE_FUNCS: dict[str, Callable[[DemoContext], None]] = {
    "data": stage_data,
    "capture": stage_capture,
    "curate": stage_curate,
    "train": stage_train,
    "eval": stage_eval,
    "serve": stage_serve,
    "report": stage_report,
}
STAGE_TITLES = {
    "data": "data: load the dataset, import every split with gold labels",
    "capture": "capture: training inputs through the capture proxy",
    "curate": "curate: normalise, scrub, split, dedupe, label, filter, leakage check",
    "train": "train: LoRA fine-tune the student",
    "eval": "eval: select on validation, score on test",
    "serve": "serve: cascade server smoke test",
    "report": "report: quality, cost, latency",
}


def run_demo(
    name: str,
    *,
    profile: str = "quick",
    live: bool = False,
    yes: bool = False,
    until: str | None = None,
    base: str | None = None,
    seed: int | None = None,
    max_usd: float | None = None,
    backend: str = "mlx",
    log: Callable[[str], Any] = print,
) -> dict[str, Any]:
    if name not in DEMOS:
        raise DemoError(f"unknown demo {name!r}; choose one of {', '.join(DEMOS)}")
    if profile not in PROFILES:
        raise DemoError(f"--profile must be one of {', '.join(PROFILES)}")
    if until is not None and until not in STAGES:
        raise DemoError(f"--until must be one of {', '.join(STAGES)}")
    spec = load_task(name)
    from taskdistill.teacher.factory import resolve_mode

    mode = resolve_mode(spec, "live" if live else "replay")
    ctx = DemoContext(
        name=name, profile=profile, spec=spec, mode=mode, yes=yes, max_usd=max_usd, backend=backend,
        base=base, seed=seed, log=log,
    )  # fmt: skip
    teacher_note = (
        "replay (recorded teacher outputs; pass --live for real calls)"
        if mode == "replay"
        else f"live ({spec.teacher.model})"
    )
    log(f"taskdistill demo {name}: profile {profile}, teacher {teacher_note}, workspace {paths.home().name}/")
    stages = STAGES[: STAGES.index(until) + 1] if until else STAGES
    started = time.perf_counter()
    for i, stage in enumerate(stages, 1):
        log(f"[{i}/{len(STAGES)}] {STAGE_TITLES[stage]}")
        t0 = time.perf_counter()
        STAGE_FUNCS[stage](ctx)
        ctx.timings[stage] = round(time.perf_counter() - t0, 2)
    total = round(time.perf_counter() - started, 1)
    timing = {"demo": name, "profile": profile, "mode": mode, "stages_s": ctx.timings, "total_s": total}
    out = paths.task_home(spec.task) / f"demo_timing_{profile}.json"
    out.write_text(json.dumps(timing, indent=2) + "\n", encoding="utf-8")
    log(f"done in {total:.0f} s ({', '.join(f'{k} {v:.0f}s' for k, v in ctx.timings.items())})")
    return timing
